[package]
name = "<ZOME_NAME>"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "<ZOME_NAME>"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
holochain_serialized_bytes = { workspace = true }

<ZOME_NAME>_integrity = { workspace = true }

[dev-dependencies]
holochain = { workspace = true, features = ["wasmer-sys-cranelift", "test_utils"] }
tokio = { workspace = true }
